In [107]:
# Import necessary libraries

import numpy as np
import pandas as pd
import pandapower as pp
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import pp_heig_simulation as pp_sim
import pickle
import re
import pp_heig_simulation as pp_sim
import pp_heig_plot as pp_plot
from datetime import time

Import pickle ("trey_net_student.p")

In [108]:
# Load the pandapower network from the pickle file
net_trey = pp.from_pickle("input-data/trey_net_student.p")

# quick inspection
print(type(net_trey))
print(net_trey)

<class 'pandapower.auxiliary.pandapowerNet'>
This pandapower network includes the following parameter tables:
   - bus (13 elements)
   - load (12 elements)
   - ext_grid (1 element)
   - line (11 elements)
   - trafo (1 element)

Design of network

In [109]:
# Bus
net_trey.bus

            name   type   zone  in_service
0     STMT003438     PQ  Trafo        True
1     CDBT004764     PQ  North        True
2     CDBT003746     PQ  North        True
3     CDBT004760     PQ  North        True
4     CDBT012139     PQ  North        True
5     CDBT900784     PQ  North        True
6     CDBT901452     PQ  South        True
7     CDBT004774     PQ  South        True
8     CDBT901604     PQ  South        True
9     CDBT016055     PQ  South        True
10            N1     PQ  South        True
11         60437     PQ  South        True
12  STMT003438HV  Slack  Trafo        True

In [123]:
# load profile

## Create parameter table for cable types
name = pd.DataFrame(
    {
        "name": [
            "STMT003438",  # 2.854e-6,
            "CDBT004764",  # 3.995e-6,
            "CDBT003746",  # 1.712e-6,
            "CDBT004760",  # 2.283e-6,
            "CDBT012139",  # 2.283e-6,
            "CDBT900784",  # 2.283e-6,
            "CDBT901452",  # 2.854e-6,
            "CDBT004774",  # 2.283e-6,
            "CDBT901604",  # 0.571e-6,
            "CDBT016055",  # 2.283e-6,
            "N1",  # 0.571e-6,
            "60437",  # 0.571e-6,
        ],
        "p_mw": [
            2.854e-6,
            3.995e-6,
            1.712e-6,
            2.283e-6,
            2.283e-6,
            2.283e-6,
            2.854e-6,
            2.283e-6,
            0.571e-6,
            2.283e-6,
            0.571e-6,
            0.571e-6,
        ],
        "q_mvar": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
        ],
    }
)

## Merge net_trey.load with cable_types on "name"
net_trey.load = net_trey.load.merge(name, on="name", how="left")

## Show updated net_trey.load
net_trey.load

,name,bus,const_z_percent,const_i_percent,sn_mva,in_service,type,p_mw_x,p_mw_y,q_mvar
0,STMT003438,0,0.0,0.0,None,True,wye,2.854000e-06,2.854000e-06,0.0
1,CDBT004764,1,0.0,0.0,None,True,wye,3.995000e-06,3.995000e-06,0.0
2,CDBT003746,2,0.0,0.0,None,True,wye,1.712000e-06,1.712000e-06,0.0
3,CDBT004760,3,0.0,0.0,None,True,wye,2.283000e-06,2.283000e-06,0.0
4,CDBT012139,4,0.0,0.0,None,True,wye,2.283000e-06,2.283000e-06,0.0
5,CDBT900784,5,0.0,0.0,None,True,wye,2.283000e-06,2.283000e-06,0.0
6,CDBT901452,6,0.0,0.0,None,True,wye,2.854000e-06,2.854000e-06,0.0
7,CDBT004774,7,0.0,0.0,None,True,wye,2.283000e-06,2.283000e-06,0.0
8,CDBT901604,8,0.0,0.0,None,True,wye,5.710000e-07,5.710000e-07,0.0
9,CDBT016055,9,0.0,0.0,None,True,wye,2.283000e-06,2.283000e-06,0.0
10,N1,10,0.0,0.0,None,True,wye,5.710000e-07,5.710000e-07,0.0
11,60437,11,0.0,0.0,None,True,wye,5.710000e-07,5.710000e-07,0.0

In [111]:
# ext_grid
net_trey.ext_grid

,name,vm_pu,va_degree,slack_weight,s_sc_max_mva,s_sc_min_mva,rx_min,rx_max,r0x0_max,x0x_max,in_service
0,ext_grid_0,1.0,0.0,1.0,100.0,None,None,0.1,2.0,2.0,True

In [112]:
# Line
net_trey.line

              name  from_bus  to_bus  g_us_per_km   df std_type  in_service
0     GKN3x150_150         0       1          0.0  1.0     None        True
1   GKN3x150_150_2         1       2          0.0  1.0     None        True
2       GKN3X95_95         1       3          0.0  1.0     None        True
3       GKT3X50_50         3       4          0.0  1.0     None        True
4     GKT3X50_50_2         4       5          0.0  1.0     None        True
5   GKN3x150_150_3         0       6          0.0  1.0     None        True
6     GKN3X95_95_2         6       7          0.0  1.0     None        True
7   GKN3x150_150_4         7       8          0.0  1.0     None        True
8       GKN3X50_50         7       9          0.0  1.0     None        True
9     GKN3X50_50_2         6      10          0.0  1.0     None        True
10    GKN3X240_240         0      11          0.0  1.0     None        True

In [113]:
# Use the datasheet to create a dictionary with line parameters

## Create new column "cable_type" by removing the unwanted value (_x) use to differentiate each line from "name" with regex
# re.sub replaces the matches with the given substitute string
# First argument: regex pattern
# Second argument: substitute string
# Third argument: input string

net_trey.line.insert(
    0,
    "length_km",
    [0.180, 0.1, 0.115, 0.08, 0.09, 0.135, 0.1, 0.205, 0.085, 0.255, 0.340],
)
net_trey.line["cable_type"] = net_trey.line.apply(
    lambda x: re.sub(r"_[0-9]$", "", x["name"]), axis=1
)

## Create parameter table for cable types
cable_types = pd.DataFrame(
    {
        "cable_type": [
            "GKN3x150_150",
            "GKN3X95_95",
            "GKN3X50_50",
            "GKN3X240_240",
            "GKT3X50_50",
        ],
        "r_ohm_per_km": [0.124, 0.193, 0.387, 0.0754, 0.387],
        "x_ohm_per_km": [0.07, 0.07, 0.07, 0.07, 0.07],
        "c_uf_per_km": [349, 338, 298, 346, 298],
        "max_i_ka": [0.4, 0.252, 0.17, 0.512, 0.17],
    }
)

## Merge net_trey.line with cable_types on "cable_type"
net_trey.line = net_trey.line.merge(cable_types, on="cable_type", how="left")

## Show updated net_trey.line
net_trey.line

# les valeurs de max_i_ka sont les valeur pour des cables enterrés. en effet le reseau suisse est majoriterrement souterrain en zone urbaine.

,length_km,name,from_bus,to_bus,g_us_per_km,df,std_type,in_service,cable_type,r_ohm_per_km,x_ohm_per_km,c_uf_per_km,max_i_ka
0,0.180,GKN3x150_150,0,1,0.0,1.0,None,True,GKN3x150_150,0.1240,0.07,349,0.400
1,0.100,GKN3x150_150_2,1,2,0.0,1.0,None,True,GKN3x150_150,0.1240,0.07,349,0.400
2,0.115,GKN3X95_95,1,3,0.0,1.0,None,True,GKN3X95_95,0.1930,0.07,338,0.252
3,0.080,GKT3X50_50,3,4,0.0,1.0,None,True,GKT3X50_50,0.3870,0.07,298,0.170
4,0.090,GKT3X50_50_2,4,5,0.0,1.0,None,True,GKT3X50_50,0.3870,0.07,298,0.170
5,0.135,GKN3x150_150_3,0,6,0.0,1.0,None,True,GKN3x150_150,0.1240,0.07,349,0.400
6,0.100,GKN3X95_95_2,6,7,0.0,1.0,None,True,GKN3X95_95,0.1930,0.07,338,0.252
7,0.205,GKN3x150_150_4,7,8,0.0,1.0,None,True,GKN3x150_150,0.1240,0.07,349,0.400
8,0.085,GKN3X50_50,7,9,0.0,1.0,None,True,GKN3X50_50,0.3870,0.07,298,0.170
9,0.255,GKN3X50_50_2,6,10,0.0,1.0,None,True,GKN3X50_50,0.3870,0.07,298,0.170
10,0.340,GKN3X240_240,0,11,0.0,1.0,None,True,GKN3X240_240,0.0754,0.07,346,0.512

In [114]:
# tranformer
net_trey.trafo

,name,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,i0_percent,vector_group,vk0_percent,vkr0_percent,mag0_percent,mag0_rx,si0_hv_partial,shift_degree,tap_side,tap_neutral,tap_min,tap_max,tap_step_percent,tap_step_degree,tap_pos,tap_phase_shifter,parallel,std_type,df,in_service
0,STMT003438,12,0,0.63,18.3,0.42,4.0,0.42,0.65,1.8,Dyn,3.0,0.75,0.3,1.9,1.9,0.0,lv,0,-3,3,2.0,0.0,-3,False,1,None,1.0,True

In [115]:
# Bus profile

## Create parameter table for cable types
net_trey.bus["vn_kv"] = 0.4

net_trey.bus.loc[net_trey.bus["name"] == "STMT003438HV", "vn_kv"] = 18


net_trey.bus

            name   type   zone  in_service  vn_kv
0     STMT003438     PQ  Trafo        True    0.4
1     CDBT004764     PQ  North        True    0.4
2     CDBT003746     PQ  North        True    0.4
3     CDBT004760     PQ  North        True    0.4
4     CDBT012139     PQ  North        True    0.4
5     CDBT900784     PQ  North        True    0.4
6     CDBT901452     PQ  South        True    0.4
7     CDBT004774     PQ  South        True    0.4
8     CDBT901604     PQ  South        True    0.4
9     CDBT016055     PQ  South        True    0.4
10            N1     PQ  South        True    0.4
11         60437     PQ  South        True    0.4
12  STMT003438HV  Slack  Trafo        True   18.0

**Plot network**

In [ ]:
net_trey

,name,bus,const_z_percent,const_i_percent,sn_mva,in_service,type,p_mw
0,STMT003438,0,0.0,0.0,None,True,wye,2.854000e-06
1,CDBT004764,1,0.0,0.0,None,True,wye,3.995000e-06
2,CDBT003746,2,0.0,0.0,None,True,wye,1.712000e-06
3,CDBT004760,3,0.0,0.0,None,True,wye,2.283000e-06
4,CDBT012139,4,0.0,0.0,None,True,wye,2.283000e-06
5,CDBT900784,5,0.0,0.0,None,True,wye,2.283000e-06
6,CDBT901452,6,0.0,0.0,None,True,wye,2.854000e-06
7,CDBT004774,7,0.0,0.0,None,True,wye,2.283000e-06
8,CDBT901604,8,0.0,0.0,None,True,wye,5.710000e-07
9,CDBT016055,9,0.0,0.0,None,True,wye,2.283000e-06
10,N1,10,0.0,0.0,None,True,wye,5.710000e-07
11,60437,11,0.0,0.0,None,True,wye,5.710000e-07

In [117]:
pp_plot.plot_power_network(
    net=net_trey,
    plot_title="Test_network",
    filename="",
)

AttributeError: 'DataFrame' object has no attribute 'bus'